check for incorrect App permissions and display dropbox_uploader.sh errors

diff --git a/dropback/Dockerfile b/dropback/Dockerfile
--- a/dropback/Dockerfile
+++ b/dropback/Dockerfile
@@ -4,7 +4,16 @@ FROM $BUILD_FROM
 COPY run.sh /
 RUN chmod a+x /run.sh
 
-RUN curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o /dropbox_uploader.sh
+# get a copy of dropbox_uploader.sh and amend the end of file to output errors
+#
+# if [[ $ERROR_STATUS -ne 0 ]]; then
+#     cat $RESPONSE_FILE | sed -n -e '/^[[:space:]]*$/,$p' | sed '/^$/d'
+# fi
+# remove_temp_files
+# exit $ERROR_STATUS
+#
+RUN curl --silent "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" | head -n 1827 > /dropbox_uploader.sh
+RUN echo 'if [[ $ERROR_STATUS -ne 0 ]]; then cat $RESPONSE_FILE | sed -n -e '"'"'/^[[:space:]]*$/,$p\'"'"' | sed '"'"'/^$/d\'"'"';fi;remove_temp_files;exit $ERROR_STATUS' >> /dropbox_uploader.sh
 RUN chmod a+x /dropbox_uploader.sh
 
 CMD [ "/run.sh" ]
